### model
model_name_or_path: deepseek-ai/deepseek-coder-1.3b-instruct

### method
stage: sft
do_train: true
do_eval: true
do_predict: false
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: output

template: deepseekcoder
cutoff_len: 2048
max_samples: 10000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/nopy_timecp_final_sft_deepseek-coder-1.3b-base

logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 2
learning_rate: 5.0e-6
num_train_epochs: 4.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.00005
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50000
